production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  update_daily_boardgame_deals:
    class: UpdateDailyBoardgameDealsJob
    queue: background
    schedule: every hour
  update_boardgame_deals:
    class: BoardgameDeals::RefreshViewJob
    queue: background
    schedule: every hour
  update_boardgame_ranks:
    class: UpdateBoardgameRanksJob
    queue: background
    schedule: every day at 1 AM
